corner-radius = 12
rounded-corners-exclude = [
    "class_g = 'Polybar'"
];

# Shadows
shadow = true
shadow-radius = 12
shadow-opacity = 0.4
shadow-offset-x = -7
shadow-offset-y = -7
shadow-exclude = [
    "class_g = 'Polybar'"
];

# Fading
fading = true
fade-in-step = 0.06
fade-out-step = 0.04
fade-delta = 8

# Blur
backend = "glx"
blur-method = "dual_kawase"
blur-strength = 4
blur-background = true
blur-background-exclude = [
    "class_g = 'Polybar'"
];

# Animations
animations = true
animation-stiffness = 200
animation-dampening = 25
animation-mass = 1

# Dimming
inactive-dim = 0.15

vsync = true
