[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_dir_first = true
show_hidden = false
show_symlink = true
scrolloff = 5
linemode = "size"

[preview]
wrap = "no"
tab_size = 2
image_filter = "lanczos3"
image_quality = 80
